image: maven:latest

stages:
  - build
  - test
  - staging
  - release
  - production

build-job:
  stage: build
  script:
    - echo "Building Application!"

unit-tests:
  stage: test
  script:
    - mvn test
  only:
    - merge_requests
    - main
    - feature/websocket-chatroom

sonar-scan:
  stage: test
  script:
    - echo "Sonar Scan Checking Quality Gates!"
  needs:
    - unit-tests
  only:
    - merge_requests
    - main
    - feature/websocket-chatroom

load-tests:
  stage: test
  script:
    - echo "How much load can this application handle?"

# Add deployment image scans
# Add J Frog Scan
# Add X-Ray Scan

deploy-staging:
  stage: staging
  script:
    - echo "Deploying to Staging Environment!

release-ticket:
  stage: release
  needs:
    - deploy-staging
  script:
    - echo "Create release ticket!

deploy-prod:
  stage: production
  script:
    - echo "Deploying to Production Environment!"
  when: manual
