#Pipeline to support the CI/CD process

image: maven:latest

stages:
  - build
  - test
  - deploy-staging
  - release-ticket
  - deploy-production

build-job:
  stage: build
  script:
    - echo "Building the application"

unit-tests:
  stage: test
  script:
    - mvn test
  only:
    - merge_requests

sonar-scan:
  stage: test
  script:
    - echo "Running SonarQube Scan"
  needs:
    - unit-tests
  only:
    - merge_requests

load-tests:
  stage: test
  script:
    - echo "Running load tests"

# Add deployment image scans
# Add X-Ray scan job for Maven
#Add J-Frog scan job for Maven

deploy-staging:
  stage: deploy-staging
  script:
    - echo "Deploying to Staging Environment
  environment: staging

# Add release ticket creation job
release-ticket:
  stage: release-ticket
  script:
    - echo "Create release ticket"

deploy-prod:
  stage: deploy-production
  script:
    - echo "Deploying to Production Environment"
  environment: production
  when: manual
