apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: CHATROOM
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chatroom
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70
